name: Publish images to GHCR
on:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        cuda-version: ["12.4.1", "12.6.3", "12.8.1"]
    steps:
      - name: Clean up unneeded tooling
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          swap-size-mb: 1024
          overprovision-lvm: "true"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish image
        uses: ./.github/actions/docker-publish-action
        with:
          branch: ${{ github.ref_name }}
          commit_sha: ${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: riogesulgon/framepack-lite
          cuda_version: ${{ matrix.cuda-version }}
